name: Build Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [esp32s3, esp32c3]
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v5.3
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Build & merge
        run: |
          git config --global --add safe.directory '*'
          . /opt/esp/idf/export.sh
          idf.py set-target ${{ matrix.target }}
          idf.py build
          cd build
          esptool.py --chip ${{ matrix.target }} merge_bin -o merged.bin \
            0x0 bootloader/bootloader.bin \
            0x8000 partition_table/partition-table.bin \
            0x10000 3nmos_no_wifi.bin

      - name: Upload merged.bin
        uses: actions/upload-artifact@v4
        with:
          name: merged-firmware-${{ matrix.target }}
          path: build/merged.bin
